kind: Deployment
apiVersion: apps/v1
metadata:
  name: python-app
  labels:
    backstage.io/kubernetes-id: python-app
    app.kubernetes.io/component: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/component: backstage
  template:
    metadata:
      labels:
        app: python-app
        backstage.io/kubernetes-id: python-app
        app.kubernetes.io/component: backstage
    spec:
      containers:
        - name: python-app
          image: quay.io/szigmon/python-app:latest
          ports:
            - name: http-5000
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
