kind: Service
apiVersion: v1
metadata:
  labels:
    app: python-app
    app.kubernetes.io/component: backstage
    backstage.io/kubernetes-id: python-app
  name: python-app
spec:
  ports:
    - name: http-5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: python-app
    app.kubernetes.io/component: backstage
    
