apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "python-app"
spec:
  destination:
    namespace: python-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/base
    repoURL: https://github.com/ocpcluster/python-app
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
